# Generated by Django 5.2.4 on 2025-08-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='active_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Активных'),
        ),
        migrations.AddField(
            model_name='resident',
            name='completed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Пройдено'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='phone',
            field=models.CharField(max_length=50, unique=True, verbose_name='Телефон'),
        ),
    ]
