# Generated by Django 5.2.4 on 2025-08-01 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_resident_active_count_resident_completed_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='core.resident'),
        ),
    ]
