# Generated by Django 5.2.4 on 2025-08-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_participation_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Завершён'),
        ),
    ]
