# Generated by Django 5.2.4 on 2025-08-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='status',
            field=models.CharField(choices=[('paid', 'Оплачено'), ('reserved', 'Забронировано'), ('partial', 'Оплачено частично')], default='reserved', max_length=20, verbose_name='Статус'),
        ),
    ]
