# Generated by Django 5.2.4 on 2025-08-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_participation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='came',
            field=models.BooleanField(default=False, verbose_name='Пришёл'),
        ),
        migrations.AddField(
            model_name='participation',
            name='notified',
            field=models.BooleanField(default=False, verbose_name='Уведомлен'),
        ),
    ]
